name: Docker Build and Scan
on:
  push:
    branches:
      - main

jobs:
  docker-build-scan:
    name: Docker Build and Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .
        env:
          DOCKER_BUILDKIT: 1

      - name: Install Snyk
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO- https://static.snyk.io/cli/latest/snyk-linux | sudo tee /usr/local/bin/snyk > /dev/null
          sudo chmod +x /usr/local/bin/snyk
          snyk --version

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk auth $SNYK_TOKEN

      - name: Scan Docker Image
        run: |
          snyk container test myapp:latest --severity-threshold=low --json --file=Dockerfile --project-name=SkillsViz > snyk_scan_results.json
          cat snyk_scan_results.json  # Display the scan results in the console

      - name: Upload Snyk Scan Results as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-scan-results
          path: snyk_scan_results.json

      - name: Monitor Snyk Docker Project
        run: |
          snyk monitor --docker myapp:latest --project-name=SkillsViz
